export const actions = {
  PAGE_LOADING: 'PAGE_LOADING',
  STOP_PAGE_LOADING: 'STOP_PAGE_LOADING',
  ALERT_SUCCESS: 'ALERT_SUCCESS',
  ALERT_INFO: 'ALERT_INFO',
  ALERT_ERROR: 'ALERT_ERROR',
  ALERT_WARNING: 'ALERT_WARNING',
  ALERT_CLOSE: 'ALERT_CLOSE',
  SET_INIT_USER_INFO: 'SET_INIT_USER_INFO',
  LOG_OUT_USER: 'LOG_OUT_USER',
  SET_TOKEN: 'SET_TOKEN'
}